### ISSUE TITLE
Vue 3 migration

### ISSUE THREAD

**Issue by MrLucio** [gentritabazi/vue-lumen-starter#60]
Hello,
as the title says I was wondering if it was possible to migrate this wonderful project to Vue 3.

Unfortunately some of the libraries that have been used don't have a proper Vue 3 support, like vue-notification (@kyvg/vue3-notification could be used instead).

**Comment by MrLucio** [comment]
I created #61 to keep track of the changes

**Comment by gentritabazi** [comment]
Feel free to work on a PR.
